name: SDK E2E test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "Run SDK-E2E"
