name: SDK Dependency E2E Test

on:
  push:
    branches:
      - renovate/**

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List Cases
        id: dispatch-cases
        working-directory: packages/cli/tests/e2e
        run: |
          cases=`find ./bot ./frontend -path "*.tests.ts" -and \
            -not '(' -path '*/*.dotnet.tests.ts' -or -path '*/Blazor*' ')' \
            | jq -Rsc '[split("\n") | .[]| select(.!="")]'`
          echo "cases=$cases" >> $GITHUB_OUTPUT
          
      - name: E2E Test
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/e2e-test.yml \
           -d '{"ref":"${{ github.ref_name }}","inputs":{"cases":"${{ steps.dispatch-cases.outputs.cases }}"}}'
           
  sdk-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: SDK E2E Test
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/sdk-e2e-test.yml \
           -d '{"ref":"${{ github.ref_name }}"}'
        
